language: cpp

dist: bionic
sudo: required

matrix:
  include:
    - name: "default gcc with coverage"
      compiler: gcc
      env:
        - COVERAGE=1
        - CMAKE_OPTS="-DENABLE_COVERAGE=ON"
    - name: "default clang"
      compiler: clang

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build && cd build
  - cmake $CMAKE_OPTS ..
  - cmake --build .

after_success:
  - if [ "${COVERAGE}" == "1" ]; then
      coveralls --exclude build --exclude examples --exclude lib --exclude tests --gcov-options '\-lp';
    fi  