language: cpp

dist: bionic

matrix:
  include:
    # default gcc with coverage
    - compiler: gcc
      env:
        - COVERAGE=1
        - CMAKE_OPTS="-DENABLE_COVERAGE=ON"
    # default clang with clang-tidy checks
    - compiler: clang
      env:
        - CMAKE_OPTS="-DENABLE_CLANG_TIDY=ON"

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build && cd build
  - cmake $CMAKE_OPTS ..
  - cmake --build .

after_success:
  - if [ "${COVERAGE}" == "1" ]; then
      coveralls --root .. -E '.*/build/CMakeFiles/.*' -E '.*/build/lib/.*' -E '.*/examples/.*' -E '.*/lib/.*' -E '.*/tests/.*' --gcov-options '\-lp';
    fi