version: "{build}"

install:
  - git submodule update --init --recursive
 
image:
  - Visual Studio 2017
  # - Visual Studio 2015
  # - Visual Studio 2013
  
configuration:
  - Debug
  - Release

environment:
  matrix:
  - arch: Win32
  - arch: Win64

init:
  - echo %APPVEYOR_BUILD_WORKER_IMAGE% - %configuration% - %arch%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (set vs=Visual Studio 15 2017)
  # - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (set vs=Visual Studio 14 2015)
  # - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" (set vs=Visual Studio 12 2013)
  - if "%arch%"=="Win64" (set generator="%vs% Win64")
  - if "%arch%"=="Win32" (set generator="%vs%")
  - echo %generator%
 
before_build:
  - mkdir build
  - cd build
  - cmake -DUAPP_BUILD_TESTS=ON -DUAPP_BUILD_EXAMPLES=ON .. -G %generator%

build_script:
  - cmake --build . --config %configuration%