name: CI

on: [push, pull_request]

jobs:
  linux:
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
    name: Linux ${{ matrix.config.name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          # prettier-ignore
          - { name: GCC 9,      CC: gcc-9,    CXX: g++-9,      flags: ""}
          - { name: GCC 10,     CC: gcc-10,   CXX: g++-10,     flags: ""}
          - { name: Clang 10,   CC: clang-10, CXX: clang++-10, flags: "" }
          - { name: Clang 11,   CC: clang-11, CXX: clang++-11, flags: "" }
          - { name: Clang 12,   CC: clang-12, CXX: clang++-12, flags: "" }
          - { name: Clang-Tidy, CC: clang-12, CXX: clang++-12, flags: "-DUAPP_ENABLE_CLANG_TIDY=ON" }
          - { name: ASan,       CC: clang-12, CXX: clang++-12, flags: "-DUAPP_ENABLE_SANITIZER_ADDRESS=ON" }
          - { name: LSan,       CC: clang-12, CXX: clang++-12, flags: "-DUAPP_ENABLE_SANITIZER_LEAK=ON" }
          - { name: TSan,       CC: clang-12, CXX: clang++-12, flags: "-DUAPP_ENABLE_SANITIZER_THREAD=ON" }
          - { name: UBSan,      CC: clang-12, CXX: clang++-12, flags: "-DUAPP_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON" }
          - { name: Coverage,   CC: gcc,      CXX: g++,        flags: "-DUAPP_ENABLE_COVERAGE=ON" }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compile and run tests
        env:
          CC: ${{ matrix.config.CC }}
          CXX: ${{ matrix.config.CXX }}
        run: |
          mkdir build
          cd build
          cmake -DUAPP_BUILD_TESTS=ON -DUAPP_BUILD_EXAMPLES=ON ${{ matrix.config.flags }} ..
          cmake --build .
      - name: Upload coverage results to coveralls.io
        if: ${{ github.ref == 'refs/heads/master' && matrix.config.name == 'Coverage' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pip install cpp-coveralls
          coveralls \
            -E '.*/3rdparty/.*' \
            -E '.*/build/.*' \
            -E '.*/doc/.*' \
            -E '.*/examples/.*' \
            -E '.*/tests/.*' \
            --gcov-options '\-lp';

  windows:
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
    name: Windows ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: Visual Studio 16 2019, os: windows-2019 }
          - { name: Visual Studio 17 2022, os: windows-2022 }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compile and run tests
        run: |
          mkdir build
          cd build
          cmake -DUAPP_BUILD_TESTS=ON -DUAPP_BUILD_EXAMPLES=ON ..
          cmake --build . --config RelWithDebInfo

  macos:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    name: macOS ${{ matrix.config.name }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: AppleClang 14, CC: clang, CXX: clang++ }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compile and run tests
        env:
          CC: ${{ matrix.config.CC }}
          CXX: ${{ matrix.config.CXX }}
        run: |
          mkdir build
          cd build
          cmake -DUAPP_BUILD_TESTS=ON -DUAPP_BUILD_EXAMPLES=ON ${{ matrix.config.flags }} ..
          cmake --build .
