name: CI

on: [push, pull_request]

jobs:
  linux:
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
    name: Linux ${{ matrix.config.name }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          # prettier-ignore
          - { name: GCC 9,      CC: gcc-9,    CXX: g++-9,      flags: ""}
          - { name: GCC 10,     CC: gcc-10,   CXX: g++-10,     flags: ""}
          - { name: GCC 11,     CC: gcc-11,   CXX: g++-11,     flags: ""}
          - { name: GCC 12,     CC: gcc-12,   CXX: g++-12,     flags: ""}
          - { name: Clang 12,   CC: clang-12, CXX: clang++-12, flags: "" }
          - { name: Clang 13,   CC: clang-13, CXX: clang++-13, flags: "" }
          - { name: Clang 14,   CC: clang-14, CXX: clang++-14, flags: "" }
          - { name: Clang-Tidy, CC: clang-14, CXX: clang++-14, flags: "-DUAPP_ENABLE_CLANG_TIDY=ON" }
          - { name: ASan,       CC: clang-14, CXX: clang++-14, flags: "-DUAPP_ENABLE_SANITIZER_ADDRESS=ON" }
          - { name: LSan,       CC: clang-14, CXX: clang++-14, flags: "-DUAPP_ENABLE_SANITIZER_LEAK=ON" }
          - { name: TSan,       CC: clang-14, CXX: clang++-14, flags: "-DUAPP_ENABLE_SANITIZER_THREAD=ON" }
          - { name: UBSan,      CC: clang-14, CXX: clang++-14, flags: "-DUAPP_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON" }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compile and run tests
        env:
          CC: ${{ matrix.config.CC }}
          CXX: ${{ matrix.config.CXX }}
        run: |
          mkdir build
          cd build
          cmake -DUAPP_BUILD_TESTS=ON -DUAPP_BUILD_EXAMPLES=ON ${{ matrix.config.flags }} ..
          cmake --build .

  linux-coverage:
    name: Linux Coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install requirements
        run: pip install gcovr~=6.0
      - name: Compile and run tests
        run: |
          mkdir build
          cd build
          cmake -DUAPP_BUILD_TESTS=ON -DUAPP_ENABLE_COVERAGE=ON ..
          cmake --build .
      - name: Coverage report (text)
        run: cmake --build build --target open62541pp_coverage_report
      - name: Coverage report (xml)
        run: cmake --build build --target open62541pp_coverage_report_xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage.xml

  windows:
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
    name: Windows ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: Visual Studio 16 2019, os: windows-2019 }
          - { name: Visual Studio 17 2022, os: windows-2022 }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compile and run tests
        run: |
          mkdir build
          cd build
          cmake -DUAPP_BUILD_TESTS=ON -DUAPP_BUILD_EXAMPLES=ON ..
          cmake --build . --config RelWithDebInfo

  macos:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    name: macOS ${{ matrix.config.name }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: AppleClang 14, CC: clang, CXX: clang++ }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compile and run tests
        env:
          CC: ${{ matrix.config.CC }}
          CXX: ${{ matrix.config.CXX }}
        run: |
          mkdir build
          cd build
          cmake -DUAPP_BUILD_TESTS=ON -DUAPP_BUILD_EXAMPLES=ON ${{ matrix.config.flags }} ..
          cmake --build .
