name: Doc

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  doc:
    runs-on: ubuntu-22.04
    steps:
      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build doc with CMake
        run: |
          mkdir build
          cd build
          cmake -DUAPP_BUILD_DOCUMENTATION=ON ..
          cmake --build . --target open62541pp_doc
      - name: Deploy
        if: ${{ github.event_name == 'release' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/doc_html
