name: Compatibility

on: [push, pull_request]

jobs:
  external-open62541:
    name: open62541 ${{ matrix.version }} (${{ matrix.build }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [v1.0, v1.1, v1.2, v1.3]
        build: ["static", "shared"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout open62541 version ${{ matrix.version }}
        uses: actions/checkout@v3
        with:
          repository: open62541/open62541
          ref: ${{ matrix.version }}
          path: open62541
          submodules: recursive
      - name: Install open62541
        run: |
          cd open62541
          mkdir build
          cd build
          cmake \
            -DBUILD_SHARED_LIBS=${{ matrix.build == 'shared' }} \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DUA_NAMESPACE_ZERO=FULL \
            ..
          cmake --build .
          sudo cmake --install .
      - name: Compile and run tests
        run: |
          mkdir build
          cd build
          cmake -DUAPP_BUILD_TESTS=ON -DUAPP_BUILD_EXAMPLES=ON -DUAPP_INTERNAL_OPEN62541=OFF ..
          cmake --build .
