name: Compatibility

on: [push, pull_request]

jobs:
  external-open62541:
    name: >-
      ${{ matrix.version }}
      (${{ matrix.build_type }},
      ${{ matrix.library_type }},
      ${{ matrix.amalgamation && 'amalgamated' || 'default' }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - v1.0.6
          - v1.1.6
          - v1.2.8
          - v1.3.7
        build_type: ["Debug", "Release"]
        library_type: ["static", "shared"]
        amalgamation: [false, true]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout open62541 version ${{ matrix.version }}
        uses: actions/checkout@v3
        with:
          repository: open62541/open62541
          ref: ${{ matrix.version }}
          path: open62541
          submodules: recursive
      - uses: aminya/setup-cpp@v1
        with:
          ninja: true
      - name: Build & install open62541
        env:
          CFLAGS: "-Wstrict-overflow=0" # disable strict-overflow error in v1.1
        run: |
          cd open62541
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DBUILD_SHARED_LIBS=${{ matrix.library_type == 'shared' }} \
            -DUA_ENABLE_AMALGAMATION=${{ matrix.amalgamation }} \
            -DUA_ENABLE_SUBSCRIPTIONS=ON \
            -DUA_ENABLE_SUBSCRIPTIONS_EVENTS=ON \
            ..
          cmake --build .
          sudo cmake --install .
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DUAPP_BUILD_TESTS=ON \
            -DUAPP_BUILD_EXAMPLES=ON \
            -DUAPP_INTERNAL_OPEN62541=OFF \
            ..
          cmake --build .
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
